/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9UsdArzVBgw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import UIExample from "./ui-example"
import { useState } from "react"

export function StoryList({ stories }: { stories?: string[] }) {

  const [selectedStory, setSelectedStory] = useState<string | undefined>(undefined)
  if (!stories) {
    return stories
  }
  return (
    <div className="grid grid-cols-1 md:grid-cols-[300px_1fr] gap-6 p-6 md:p-10">
      <div className="bg-background rounded-lg shadow-lg overflow-hidden">
        <div className="px-4 py-3 border-b">
          <h2 className="text-lg font-semibold">User Stories</h2>
        </div>
        <div className="p-4 space-y-2 overflow-auto max-h-[500px]">
          {
            stories.map((a) => {
              return <Button variant="ghost" className="w-full text-left rounded-md px-3 py-2 hover:bg-muted transition-colors truncate" onClick={() => { setSelectedStory(a) }}>
                {a}
              </Button>
            })
          }

        </div>
      </div>
      <div className="bg-background rounded-lg shadow-lg overflow-hidden">
        <div className="px-4 py-3 border-b">
          <h2 className="text-lg font-semibold">UX Definition</h2>
          {
            selectedStory ?
              <UIExample story={selectedStory} /> : <></>
          }
        </div>
        <div className="p-4 space-y-4">
        </div>
      </div>
    </div>
  )
}
